name: Ubuntu CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    shell: bash

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@master
      with:
        repository: mu578/mu0
    - name: Run distcheck
      run: cd mk && make -f mu8.mk distcheck

# EOF